name: workflow_2-S3-AWS
on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkuot
      uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY }}
        aws-region: us-east-1

    - name: Deploy no S3
      env:
        BUCKET_NAME: ${{ secrets.AWS_BUCKET_S3_NAME }}
      run: aws s3 cp . s3://$BUCKET_NAME

