name: workflow_2-S3-AWS
on:
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: profile.chmdev.com.br
      DIST_ID: E24SNAWOYBQNT3

    steps:
    - name: Checkuot
      uses: actions/checkout@v2

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY }}
        aws-region: us-east-1

    - name: Deploy no S3
      run: aws s3 sync . s3://${{ env.BUCKET_NAME }}
    
    - name: 
      run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
    